name: News Bot

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Test mode"
        required: true
        default: "collect"
        type: choice
        options:
          - collect
          - digest

  schedule:
    # Collect news every 30 minutes
    - cron: "*/30 * * * *"

    # Daily digest at 21:35 Iran time
    # Iran = UTC+3:30
    - cron: "5 18 * * *"

jobs:

  # ==========================================================
  # COLLECT NEWS
  # ==========================================================

  collect:
    if: github.event_name == 'schedule' && github.event.schedule == '*/30 * * * *' || github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'collect'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install --disable-pip-version-check -r requirements.txt

      - name: Collect news
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python news_bot.py collect

      - name: Save collected news
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pending_news.json seen.json
          git diff --cached --quiet || git commit -m "Collect daily news"
          git push


  # ==========================================================
  # DAILY DIGEST
  # ==========================================================

  digest:
    if: github.event_name == 'schedule' && github.event.schedule == '5 18 * * *' || github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'digest'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install --disable-pip-version-check -r requirements.txt

      - name: Create daily digest
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python news_bot.py digest

      - name: Save digest state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pending_news.json seen.json
          git diff --cached --quiet || git commit -m "Create daily news digest"
          git push
